const ACTIONS_GROUP_SEPARATOR = ':v:';
const ITEMS_GROUP_SEPARATOR = ':i:';
const ACTIONS_SEPARATOR = ';';
const NAME_SEPARATOR = ':';
const NAME_TEXT_ANCHOR = '$';
const DELETED_ITEM_SEPARATOR = 'd:';
const RECEIVED_ITEM_SEPARATOR = 'r:';

export {
    ACTIONS_GROUP_SEPARATOR,
    ACTIONS_SEPARATOR,
    NAME_SEPARATOR,
    NAME_TEXT_ANCHOR,
    DELETED_ITEM_SEPARATOR,
    RECEIVED_ITEM_SEPARATOR,
    ITEMS_GROUP_SEPARATOR,
};
