const ACTIONS_GROUP_SEPARATOR = ':v:';
const ACTIONS_SEPARATOR = ';';
const NAME_SEPARATOR = ':';
const NAME_TEXT_ANCHOR = '$';

export { ACTIONS_GROUP_SEPARATOR, ACTIONS_SEPARATOR, NAME_SEPARATOR, NAME_TEXT_ANCHOR };
